### ISSUE TITLE
Downloading external python modules is not working in Windows 7

### ISSUE THREAD

**Issue by sungtae96** [jaimeMF/youtube-dl-api-server#18]
Since I'm very newbie here, it can be my fault.
However, I cannot solve this problem.

I wanna install youtube-dl-api-server on App Engine.
However, I can not download external python modules in lib.
I did ./devscripts/setup-gae.sh, but it shows some errors

So, would you please tell me how can I complete this downloading to install it on App Engine.

OS of my PC is Windows7 32bit.
I installed Python 2.7x and set PATHs for Python27 directory in C drive.
Here's my log when I ran ./devscripts/setup-gae.sh.

====================================================================
Welcome to Git (version 1.9.2-preview20140411)

Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Downloading python packages
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated
.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking youtube-dl>=2014.03.12 (from -r ./gae/gae_requirements.txt
 (line 1))
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2f2.7%2fy%2fyoutube_dl%2fyoutub
e_dl-2014.05.19-py2.py3-none-any.whl
Downloading/unpacking flask (from -r ./gae/gae_requirements.txt (line 2))
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2fsource%2ff%2fflask%2fflask-0.
10.1.tar.gz
  Running setup.py (path:D:\AppDev\Workspace_ST\youtube_dl_api_test\gae\build\fl
ask\setup.py) egg_info for package flask

    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory
 'docs'
    warning: no previously-included files matching '*.pyo' found under directory
 'docs'
    warning: no previously-included files matching '*.pyc' found under directory
 'tests'
    warning: no previously-included files matching '*.pyo' found under directory
 'tests'
    warning: no previously-included files matching '*.pyc' found under directory
 'examples'
    warning: no previously-included files matching '*.pyo' found under directory
 'examples'
    no previously-included directories found matching 'docs\_build'
    no previously-included directories found matching 'docs\_themes\.git'
Downloading/unpacking Werkzeug>=0.7 (from flask->-r ./gae/gae_requirements.txt (
line 2))
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2fsource%2fw%2fwerkzeug%2fwerkz
eug-0.9.4.tar.gz
  Running setup.py (path:D:\AppDev\Workspace_ST\youtube_dl_api_test\gae\build\We
rkzeug\setup.py) egg_info for package Werkzeug

    warning: no files found matching '*' under directory 'werkzeug\debug\templat
es'
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory
 'docs'
    warning: no previously-included files matching '*.pyo' found under directory
 'docs'
    warning: no previously-included files matching '*.pyc' found under directory
 'tests'
    warning: no previously-included files matching '*.pyo' found under directory
 'tests'
    warning: no previously-included files matching '*.pyc' found under directory
 'examples'
    warning: no previously-included files matching '*.pyo' found under directory
 'examples'
    no previously-included directories found matching 'docs\_build'
Downloading/unpacking Jinja2>=2.4 (from flask->-r ./gae/gae_requirements.txt (li
ne 2))
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2fsource%2fj%2fjinja2%2fjinja2-
2.7.2.tar.gz
  Running setup.py (path:D:\AppDev\Workspace_ST\youtube_dl_api_test\gae\build\Ji
nja2\setup.py) egg_info for package Jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'do
cs\_build'
    warning: no previously-included files matching '*.pyc' found under directory
 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory
 'docs'
    warning: no previously-included files matching '*.pyo' found under directory
 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory
 'docs'
Downloading/unpacking itsdangerous>=0.21 (from flask->-r ./gae/gae_requirements.
txt (line 2))
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2fsource%2fi%2fitsdangerous%2fi
tsdangerous-0.24.tar.gz
  Running setup.py (path:D:\AppDev\Workspace_ST\youtube_dl_api_test\gae\build\it
sdangerous\setup.py) egg_info for package itsdangerous

    warning: no previously-included files matching '*' found under directory 'do
cs\_build'
Downloading/unpacking markupsafe (from Jinja2>=2.4->flask->-r ./gae/gae_requirem
ents.txt (line 2))
  Downloading MarkupSafe-0.23.tar.gz
  Storing download in cache at d:\appdev\workspace_st\youtube_dl_api_test\gae\tm
p\cache\https%3a%2f%2fpypi.python.org%2fpackages%2fsource%2fm%2fmarkupsafe%2fmar
kupsafe-0.23.tar.gz
  Running setup.py (path:D:\AppDev\Workspace_ST\youtube_dl_api_test\gae\build\ma
rkupsafe\setup.py) egg_info for package markupsafe

Successfully downloaded youtube-dl flask Werkzeug Jinja2 itsdangerous markupsafe

Copying python packages to ./gae/lib
Patching youtube_dl
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or direc
tory
.......
====================================================================

Please give me answer.
Thank you.

**Comment by jaimeMF** [comment]
Sorry for the delay, I forgot about this issue. I think it should work with the fix in 9e181342a6c745d0a0d49924d694ee7a5d162fdb.
If it doesn't work, please comment here and I'll reopen the issue. Thanks for the report.
