### ISSUE TITLE
500 Error on GAE

### ISSUE THREAD

**Issue by docsuleman** [jaimeMF/youtube-dl-api-server#25]
Hey Developers!

Thanks for making such wonderful application. I recently installed youtube-dl-api-server on GAE by using your documents as tutorial but I am receiving 500 server Error. All my libraries are up to date. and also in right directories (as far as i know). but still receiving this error.

PS: Please update youtube-dl in your example GAE application. the old one is not working since yesterday

**Comment by jaimeMF** [comment]
Works fine for me, please post the full log messages.

I have updated the GAE app, but please: use it only for testing, not for your own apps.

**Comment by docsuleman** [comment]
Yes dear I am not using for any app. i was just testing.. and i thought to let you know :)

here is log file.. 


Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~ytapi-11/0-1-2.381561582351970202/mainGAE.py", line 6, in <module>
    import youtube_dl
  File "/base/data/home/apps/s~ytapi-11/0-1-2.381561582351970202/gae/lib/youtube_dl/__init__.py", line 15, in <module>
    from .options import (
  File "/base/data/home/apps/s~ytapi-11/0-1-2.381561582351970202/gae/lib/youtube_dl/options.py", line 13, in <module>
    from .utils import (
  File "/base/data/home/apps/s~ytapi-11/0-1-2.381561582351970202/gae/lib/youtube_dl/utils.py", line 9, in <module>
    import ctypes
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named _ctypes

**Comment by jaimeMF** [comment]
Can you try replacing [this line](757d0286f5833085f6ebc/devscripts/gae-patch-youtube-dl.sh#L8) with `sed -i "s/import ${module}/()# Removed ${module} import/g" "$f" and follow again the instructions?

**Comment by docsuleman** [comment]
Running Setup-gae.sh give me this 

./devscripts/setup-gae.sh
Downloading python packages
DEPRECATION: --no-install, --no-download, --build, and --no-clean are deprecated.  See https://github.com/pypa/pip/issues/906.
Downloading/unpacking youtube-dl>=2014.03.12 (from -r ./gae/gae_requirements.txt (line 1))
  Downloading youtube_dl-2015.01.16-py2.py3-none-any.whl (780kB): 780kB downloaded
  Storing download in cache at ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F2.7%2Fy%2Fyoutube_dl%2Fyoutube_dl-2015.01.16-py2.py3-none-any.whl
Downloading/unpacking flask (from -r ./gae/gae_requirements.txt (line 2))
  Using download cache from ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FF%2FFlask%2FFlask-0.10.1.tar.gz
  Running setup.py (path:/root/youtube-dl-api-server/gae/build/flask/setup.py) egg_info for package flask

    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/_themes/.git'
Downloading/unpacking Werkzeug>=0.7 (from flask->-r ./gae/gae_requirements.txt (line 2))
  Using download cache from ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FW%2FWerkzeug%2FWerkzeug-0.9.6.tar.gz
  Running setup.py (path:/root/youtube-dl-api-server/gae/build/Werkzeug/setup.py) egg_info for package Werkzeug

    warning: no files found matching '*' under directory 'werkzeug/debug/templates'
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking Jinja2>=2.4 (from flask->-r ./gae/gae_requirements.txt (line 2))
  Using download cache from ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FJ%2FJinja2%2FJinja2-2.7.3.tar.gz
  Running setup.py (path:/root/youtube-dl-api-server/gae/build/Jinja2/setup.py) egg_info for package Jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking itsdangerous>=0.21 (from flask->-r ./gae/gae_requirements.txt (line 2))
  Using download cache from ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fi%2Fitsdangerous%2Fitsdangerous-0.24.tar.gz
  Running setup.py (path:/root/youtube-dl-api-server/gae/build/itsdangerous/setup.py) egg_info for package itsdangerous

    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking markupsafe (from Jinja2>=2.4->flask->-r ./gae/gae_requirements.txt (line 2))
  Using download cache from ./gae/tmp/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2FM%2FMarkupSafe%2FMarkupSafe-0.23.tar.gz
  Running setup.py (path:/root/youtube-dl-api-server/gae/build/markupsafe/setup.py) egg_info for package markupsafe

Successfully downloaded youtube-dl flask Werkzeug Jinja2 itsdangerous markupsafe
Copying python packages to ./gae/lib
Patching youtube_dl
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
sed: can't read s/import fcntl/()# Removed fcntl import/g: No such file or directory
.
.
.

sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
sed: can't read s/import ctypes/()# Removed ctypes import/g: No such file or directory
.
.
.
sed: can't read s/import netrc/()# Removed netrc import/g: No such file or directory
sed: can't read s/import netrc/()# Removed netrc import/g: No such file or directory
sed: can't read s/import netrc/()# Removed netrc import/g: No such file or directory
sed: can't read s/import netrc/()# Removed netrc import/g: No such file or directory


is it normal?

**Comment by jaimeMF** [comment]
That's because you are probably using GNU sed, if you edit the file as I said it should work (I just tested it).

Anyway, I will switch to something other than sed, because the `-i` option is not compatible between the GNU and the BSD versions.

**Comment by docsuleman** [comment]
Thank you so much.. its working now.. actually the  link you shared  was broken and i edited the wrong line :) sorry my bad.. alothough its giving me another error right now .. its about ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug.. but i guess if i update YOUTUBE-DL issue will be fixed.

**Comment by jaimeMF** [comment]
My fault, it was [this line](https://github.com/jaimeMF/youtube-dl-api-server/blob/159752c8b7be14e5e7b757d0286f5833085f6ebc/devscripts/gae-patch-youtube-dl.sh#L8)

I have pushed a change that should fixed, if it doesn't work please open a new issue. Thanks for the report.

**Comment by jaimeMF** [comment]
I forgot about the other message, `./devscripts/setup-gae.sh` should upgrade youtube-dl. If it still fails check first if you can play the video in the broswer. If it works: try running `youtube-dl URL`, if that fails it should be reported to youtube-dl.
