### ISSUE TITLE
Force ipv6 on GAE

### ISSUE THREAD

**Issue by docshafiullah** [jaimeMF/youtube-dl-api-server#27]
Google App Engine is using ip address which cannot access VEVO videos and many other signature videos. This problem can be solved by using IPV6. is there any way we can force IPV6 to be used by youtube-dl-api-server?

**Comment by jaimeMF** [comment]
It works for me, maybe you are using an outdated youtube-dl version? Could you post the logs?

**Comment by docsuleman** [comment]
the problem can be fixed after

1)  updating youtube-dl as suggested by jaimeMF, 
2) in addition if problem persist, you can solve  it by setting data center to Europe instead of US. every-time you create an app on GAE. there is option for choosing data center.
