### ISSUE TITLE
Error: Server Error

### ISSUE THREAD

**Issue by pmesco** [jaimeMF/youtube-dl-api-server#39]
I have create a new issue here.

Im getting this in my app engine and i dont know how to get round of this error cause im a new user app engine.
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds.

I have read this in your documentation.
> It needs some external python modules in lib, you can download them by running ./devscripts/setup-gae.sh (it requires pip and virtualenv).

but i dont know how to i run ./devscripts/setup-gae.sh

**Comment by jaimeMF** [comment]
Once you have downloaded the source code you have to execute in a terminal from the source code directory `./devscripts/setup-gae.sh`.

**Comment by pmesco** [comment]
Well, i actually dont know how to do it, is there any software needed to do executing that codes?

**Comment by jaimeMF** [comment]
You need python, [pip](https://pip.readthedocs.org/en/stable/) and [virtualenv](https://virtualenv.readthedocs.org/en/latest/), then you can execute that command in a terminal in some Unix system (like Mac OS X, Linux or FreeBSD).

**Comment by pmesco** [comment]
Thank you.
I hope that someone can make a step by step tutorial for beginners.
