### ISSUE TITLE
Problem youtube-dl-server is hanged at running background in system

### ISSUE THREAD

**Issue by vietstar87** [jaimeMF/youtube-dl-api-server#40]
i set youtube-dl-server running on startup.
youtube-dl-server is hanged. i can't connection get link.
plz help me.
Thanks

**Comment by vietstar87** [comment]
Almost, it don't have request. why is youtube-dl-server hanged ?

**Comment by jaimeMF** [comment]
Without more info (like the a log) I can't help you. Post the output you see an the request you are doing before it gets blocked.
