### ISSUE TITLE
HTTP Error 503

### ISSUE THREAD

**Issue by ocsemp** [jaimeMF/youtube-dl-api-server#44]
Im getting "ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

is there any way to add "-4" in executing youtube-dl?

**Comment by jaimeMF** [comment]
If it still fails, please post the url you are using?
