### ISSUE TITLE
403 Error on video url after deploying on Heroku

### ISSUE THREAD

**Issue by coderkd10** [jaimeMF/youtube-dl-api-server#45]
I deployed the API Server on Heroku [here](https://youtube-dl-backend1.herokuapp.com).
It is up and running. I am able to get the info dictionary of the video at `/api/info` but I cannot access the video-urls generated (I am getting a 403 Forbidden error). This is probabaly due to the IP constraint that extracting extracting link and downloading it must be done from the same IP. 

Here is a example:
Consider the video - https://www.youtube.com/watch?v=rYEDA3JcQqw
Its info dictionary generated by the Heroku server is - https://youtube-dl-backend1.herokuapp.com/api/info?url=https://www.youtube.com/watch?v=rYEDA3JcQqw
Link for the audio of the video is  [here](https://r13---sn-p5qlsnes.googlevideo.com/videoplayback?mn=sn-p5qlsnes&ipbits=0&mm=31&pl=16&ip=54.147.11.168&fexp=9416126%2C9416891%2C9422372%2C9422596%2C9428399%2C9431012%2C9431678%2C9432055%2C9432684%2C9433096%2C9433266%2C9433380%2C9433946%2C9433999%2C9434204%2C9435527%2C9435693%2C9435876%2C9435891%2C9436212%2C9437066%2C9437163%2C9437370%2C9437553%2C9437740%2C9437856%2C9438188%2C9438244&sparams=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&id=o-APfWsi5L7WoxM-qQJta3VSBWU_kwVs-9PiDYUpKeEsyZ&mv=m&dur=233.881&mt=1465072089&itag=249&ms=au&initcwndbps=7427500&key=yt6&sver=3&nh=IgpwcjAxLmlhZDI2Kg03Mi4xNC4yMTIuMTMx&upn=3zygNVahUVE&clen=1462277&gcr=us&source=youtube&requiressl=yes&gir=yes&mime=audio%2Fwebm&keepalive=yes&expire=1465093905&lmt=1449615889776501&signature=7DD349C5C0BFA260447B95B80B7E5B1F323F974E.7B95D57CA49CC837A63AF0880AAAAC9F3798AB&ratebypass=yes), which is inaccessible and throws a 403 Forbidden status code.

I am curious is there any way to avoid this?

**Comment by jaimeMF** [comment]
You may have luck trying this: https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818.

**Comment by coderkd10** [comment]
Thanks... its working!
