### ISSUE TITLE
trying to add format in the extra parameters whitelist

### ISSUE THREAD

**Issue by eadmaster** [jaimeMF/youtube-dl-api-server#47]
I've added `'format' : str,` in the `ALLOWED_EXTRA_PARAMS` dict.
However this url still returns the full json array with all the formats:
`http://localhost/api/info?url=youtube.com/watch?v=UYCilZ8yMmU&format=m4a`

**Comment by jaimeMF** [comment]
I think the `formats` field is always the same, but the `url` and `ext` fields in the main dict will contain the info for the `m4a` format.

**Comment by eadmaster** [comment]
i don't get it, how can i force the server to return only the videos in the `m4a` format?

**Comment by jaimeMF** [comment]
> i see, so it is not possible to filter the entries in the format field via the API, correct?

No `youtube-dl` itself always return the same `formats` field and the other fields at the main dictionary contain the info of the requested format. If you are only interested in one format, you shouldn't use the `formats` field.
