### ISSUE TITLE
Outdated youtube-dl

### ISSUE THREAD

**Issue by ocsemp** [jaimeMF/youtube-dl-api-server#51]
Hi, i see that youtube-dl that api server is using is outdated.
the youtube-dl latest version is "2016.06.23.1" but the api/version shows "2016.05.10"

**Comment by jaimeMF** [comment]
I've just updated it :).

Please note that if you want to use youtube-dl-api-server for your own app, you should deploy your own server. Because the test server runs on a free GAE plan and it has limited resources.
