### ISSUE TITLE
How to merge audio and video ?

### ISSUE THREAD

**Issue by Mohamedss** [jaimeMF/youtube-dl-api-server#53]
I tried to use merge_output_format as a parameter like:
https://app-name.herokuapp.com/api/info?url=https://www.youtube.com/watch?v=Ri7-vnrJD3k&flatten=true&merge_output_format

but it seems I am not doing it right. Any help ?

Thanks

**Comment by jaimeMF** [comment]
It can't be merged because it would require to process the video on the server and stream the resulting file. The server only provides the url for the files that YouTube provides, you can then merge them on your computer.
